<hr style="height:5px;border-width:2;color:gray;background-color:#000000"> 
<center><h1>CS 144 - Spring 2025 - Homework 4</h1></center>
<center><h1>Due: Sunday, May 4, 2025 @ 11:59pm</h1></center>

## Read *all* cells carefully and answer all parts (both text and code)

### Enter your information below:

<div style="color: #000000;background-color: #EEEEFF">
    Your Name (submitter):  <br>
    Your student ID (submitter):
<br>
<br>
<b>By submitting this notebook, I assert that the work below is my own work, completed for this course.  Except where explicitly cited, none of the portions of this notebook are duplicated from anyone else's work or my own previous work.</b>
<br>    
<br>
<b>Instruction for submissions:</B> when you have completed this homework, download this .ipynb file to your computer by left-clicking on the file name, and submit to <a href="https://elearn.ucr.edu/">Canvas</A> by the deadline. 
<br>
<br>
<B>Late work:</B> Each student is granted five "late days" which can be used (in integer units) on any of the homework. If a more dire situation arises, please contact the instructor. DO NOT RESORT TO CHEATING.
</div>


<hr style="height:5px;border-width:2;color:gray;background-color:#000000"> 
<center><h1>Chapter 3: Sequence Alignment</h1></center>
<br>

Chapter 3 has a <B>LOT</B> of coding challenges. In the interest of time, we will <b>skip</b> the following coding challenges on sequence alignment in the book
<UL>
<LI><A HREF="https://cogniterra.org/lesson/51921/step/10?unit=43410">Solve the Change Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51922/step/10?unit=43411">Find the length of a longest path in the Manhattan Tourist Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51924/step/5?unit=43413">Use OutputLCS to solve the Longest Common Subsequence Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51924/step/7?unit=43413">Solve the Longest Path in a DAG Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51927/step/3?unit=43416">Solve the Edit Distance Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51927/step/5?unit=43416">Solve the Fitting Alignment Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51927/step/7?unit=43416">Solve the Overlap Alignment Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51928/step/8?unit=43417">Solve the Alignment with Affine Gap Penalties Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51929/step/12?unit=43418">Solve the Middle Edge in Linear Space Problem (for protein strings)</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51929/step/14?unit=43418">Implement LinearSpaceAlignment to solve the Global Alignment Problem for a large dataset</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51930/step/5?unit=43419">Solve the Multiple Longest Common Subsequence Problem</A></LI>
<LI><A HREF="https://cogniterra.org/lesson/51933/step/3?unit=43422">Implement Topological Ordering</A></LI>
</UL>
Those challenges above are OPTIONAL. They are good problems, but you do not need to solve it, unless you feel inclined to do so.

<hr style="height:5px;border-width:2;color:gray;background-color:#000000"> 
<center><h1>Global Sequence Alignment</h1></center>
<br>

<div style="color: #000000;background-color: #EEFFEE">
    <font size=+2>Question 1</font><font size=+1> (15 points)</font>

Solve the <A HREF="https://cogniterra.org/lesson/51926/step/3?unit=43415">Global Alignment Problem.</A> Submit your solution to the challenge on Cogniterra and paste your Python code below.
   
Notes:
<ul>
<li>There could be multiple optimal alignments for the same input, i.e., multiple alignments with the same maximum score, but the book accepts any optimal solution</li>
<li>For tracing the alignment back, you can either reconstruct the optimal path on the dynamic programming table containing the scores, or you can produce a separate table of traceback pointers</li>
</ul>
</div>

In [5]:
!wget http://www.cs.ucr.edu/~stelo/cs144/data/hw4_test1.txt

--2025-05-04 22:11:30--  http://www.cs.ucr.edu/~stelo/cs144/data/hw4_test1.txt
Resolving www.cs.ucr.edu (www.cs.ucr.edu)... 169.235.30.15
Connecting to www.cs.ucr.edu (www.cs.ucr.edu)|169.235.30.15|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18 [text/plain]
Saving to: ‘hw4_test1.txt.2’

hw4_test1.txt.2     100%[===================>]      18  --.-KB/s    in 0s      

2025-05-04 22:11:30 (2.91 MB/s) - ‘hw4_test1.txt.2’ saved [18/18]



In [16]:
## no libraries allowed except for numpy and biopython 
## no Bio.pairwise2 allowed

from Bio.Align import substitution_matrices
from numpy import zeros


#so for this we just basically need to implement the recurrence relation from class, then do the backtracking matrix after
def globalAlignment(x, y, sub, indel):
    """ Calculate the global alignment between sequences x and y using
        dynamic programming using the substitution matrix <sub>, and <indel> penalty
        Return the full dynamic programming table. """
    D = zeros((len(x)+1, len(y)+1), dtype=int) # initialize a numpy matrix with zeroes
    #first do base cases, then do the recurrence relation
    for j in range(1, len(y)+1):
        D[0][j] = D[0][j-1] +indel

    for i in range(1, len(x)+1):
        D[i][0] = D[i-1][0]+ indel

    for i in range(1, len(x)+1):
        for j in range(1, len(y)+1):
            match= D[i-1][j-1] + sub[x[i-1]][y[j-1]] #this is te diagonal
            delete = D[i-1][j] + indel
            insert = D[i][j-1] +indel
            D[i][j] =max(match, delete, insert)  #we just need to call this to find the max
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    return D

#we start at the end of the matrix, and then we check which case was used from that^
#so we can reconstruct the solution
def tracebackGlobal(V, x, y, sub, indel):
    """ Trace back the alignment from position (len(x), len(y)) in global alignment matrix V """
    align1, align2 = '', ''
    i, j = len(x), len(y) # start from the bottom right cell
    while i>0 and j>0:
        if V[i][j] == V[i-1][j-1] + sub[x[i-1]][y[j-1]]: #if its diagonal
            align1 = align1 +x[i-1]
            align2= align2 +y[j-1]
            i=i-1
            j=j-1 

        elif V[i][j] == V[i-1][j] + indel: #means theres a gap at y (u go up)
            align1 = align1 + x[i-1] #we add the character from x
            align2 = align2 +'-'
            i=i-1

        else: #gap at x
            align1 = align1 +'-' 
            align2 = align2 + y[j-1] #add the character from y
            j=j-1
    if i==0: #add edge cases, if one of them hits 0 but the other doesnt, we need to keep going (this was why I was failing my tests)
        while j>0:
            align1 =align1+'-'
            align2=align2  +y[j-1]
            j=j-1
    if j==0:
        while i>0:
            align1=align1 +x[i-1]
            align2=align2+'-'
            i=i-1
        
            
    
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    return align1[::-1]+'\n'+align2[::-1]  # reverse the strings

f = open("hw4_test15.txt", "r")                                # open the file
blosum62 = substitution_matrices.load('BLOSUM62') # possible matrices are ['BENNER22', 'BENNER6', 'BENNER74', 'BLOSUM45', 'BLOSUM50', 'BLOSUM62', 'BLOSUM80', 'BLOSUM90', 'DAYHOFF', 'FENG', 'GENETIC', 'GONNET1992', 'HOXD70', 'JOHNSON', 'JONES', 'LEVIN', 'MCLACHLAN', 'MDM78', 'NUC.4.4', 'PAM250', 'PAM30', 'PAM70', 'RAO', 'RISLER', 'SCHNEIDER', 'STR', 'TRANS']
# blosum62 is a numpy matrix
# here is how to access the substitution cost for the aminoacid pair (A,M)
#print(blosum62.get('A').get('M'))
p1 = f.readline().strip()                                     # read the first string
p2 = f.readline().strip()                                     # read the second string

M = globalAlignment(p1, p2, blosum62, -5)                     # compute the dynamic programming matrix betwen p1 and p2, using the substitution matrix and indel penalty
# The dynamic programming matrix for this input should be
#[[  0  -5 -10 -15 -20 -25 -30]
# [ -5  -2  -6 -11 -16 -21 -26]
# [-10  -3  -5  -7 -12 -12 -17]
# [-15  -8   2  -3  -7 -12 -14]
# [-20 -13  -3   6   1  -4  -9]
# [-25 -18  -8   1   7   2  -3]
# [-30 -23 -13  -4   2   6   1]
# [-35 -28 -18  -9   2   1   4]
# [-40 -33 -23 -14  -3   1  -1]
# [-45 -38 -28 -19  -8   1   0]
# [-50 -43 -33 -24 -13  -4   8]]
print(M)
print(M[len(p1),len(p2)])                                     # alignment score in on lower right corner cell
print(tracebackGlobal(M, p1, p2, blosum62, -5))               # print alignment

[[    0    -5   -10 ... -3930 -3935 -3940]
 [   -5     4    -1 ... -3921 -3926 -3931]
 [  -10    -1     1 ... -3907 -3912 -3917]
 ...
 [-3590 -3581 -3568 ...  1775  1770  1765]
 [-3595 -3586 -3573 ...  1770  1779  1774]
 [-3600 -3591 -3578 ...  1767  1774  1785]]
1785
A--C------DIMPELYFPKYFDELWIMKSIQENRCHFCSPISESIDAWERQFCDSAYSQAQWGRDPKKLEVCSDHKGFPIFDLIWSAYCT-Y-------NMGTHQAQKAF-SEQWVL----FITWQPRYTSSGGGCWAATSYR--VKPD-K-DS-YNNDKTITANNW-V----PYIKHDICIWMSHW-YESCIMQKMPTSPGRIDTSSFKGK--MHHSNHIT---D--D-QFCSPDRESGMSYQNCCCCIQRWNQMHCGKFWCHWHTWREGWIQHGMCFLDWMALWEAGKEGIEKVLRQ-------S-YVITFCDIFCATSHED---A-M----PYHADKSDYGYMGN---D-KNDRYIG-CR-EHM--VAIFIVYVWYIFE----MTILEMWIVIYVYSYVAPEFF--CCAWDYSQN-YSISVVF-VERTDNNKIPDINENSKDWGFHSQVYYYN-GSEL---YTNIAIMDGWTQQWCHSPWSHWLLMWGIILCVFAMCWMTIGRMENVQGFNNDQWMNKAEYYPFFPNMPKT-----I-IQ-LRWIFHAFNFRDYNQVQQPRMGDTQELWRILYYTHPFMIGMNSWSGEFHGHQNGRQVQCWFWCTPG-W-FH-IYKLC-GNVQCWQVRG-SAI-IPW-HENYKIKIWMMIMAEMSH--Y--A-WCHNHKIAIRHQAYHGWLGDSQNDHSGFSGMLEFIEKDHWQTERKPSLRWDAD-----IEQ-SR

<hr style="height:5px;border-width:2;color:gray;background-color:#000000"> 
<center><h1>Local Sequence Alignment</h1></center>
<br>


<div style="color: #000000;background-color: #EEFFEE">
    <font size=+2>Question 2</font><font size=+1> (15 points)</font>

Solve the <A HREF="https://cogniterra.org/lesson/34016/step/10?unit=25862">Local Alignment Problem.</A> Submit your solution to the challenge on Cogniterra and paste your Python code below.

Notes:
<ul>
<li>We are providing code to access the pam250 matrix via Biopython, so that you do not have to parse the matrix from the book</li>
<li>There could be multiple optimal alignments for the same input, i.e., multiple alignments with the same maximum score, but the book accepts any optimal solution</li>
<li>For tracing the alignment back, you can either reconstruct the optimal path on the dynamic programming table containing the scores, or you can produce a separate table of traceback pointers</li>
</ul>
</div>

In [1]:
!wget http://www.cs.ucr.edu/~stelo/cs144/data/hw4_test2.txt

--2025-05-04 22:56:56--  http://www.cs.ucr.edu/~stelo/cs144/data/hw4_test2.txt
Resolving www.cs.ucr.edu (www.cs.ucr.edu)... 169.235.30.15
Connecting to www.cs.ucr.edu (www.cs.ucr.edu)|169.235.30.15|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 15 [text/plain]
Saving to: ‘hw4_test2.txt’

hw4_test2.txt       100%[===================>]      15  --.-KB/s    in 0s      

2025-05-04 22:56:56 (2.37 MB/s) - ‘hw4_test2.txt’ saved [15/15]



In [1]:
## no libraries allowed except for numpy, itertools and biopython
## no Bio.pairwise2 allowed

from numpy import zeros, where, unravel_index, argmax, shape
from Bio.Align import substitution_matrices

def localAlignment(x, y, sub, indel):
    ''' Calculate local alignment values of sequences x and y using
        dynamic programming.  Returns the dynamic programming table and
        the matrix of traceback pointer (0,1,2,3) where 0: stop, 1: diagonal, 2: up, 3: left '''
    D = zeros((len(x)+1, len(y)+1), dtype=int) # numpy matrix for scores
    T = zeros((len(x)+1, len(y)+1), dtype=int) # numpy matrix for pointers (0: stop, 1: diagonal, 2: up, 3: left)
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    ## YOUR CODE HERE

    for i in range(1, len(x)+1):
        for j in range(1, len(y)+1):  #same as previous question
            match= D[i-1][j-1] + sub[x[i-1]][y[j-1]] #this is te diagonal
            delete = D[i-1][j] + indel
            insert = D[i][j-1] +indel
            score =max(0,match, delete, insert)
            D[i][j] =score  #we just need to call this to find the max
            if score ==0:
                T[i][j]=0  #here we just use the pointers so we can access the local
            elif score == match:
                T[i][j]=1
            elif score == delete:
                T[i][j]=2
            else:
                T[i][j] =3
    return D,T

def tracebackLocal(T, x, y, i, j):
    """ Trace back the alignment from position (i,j) in
        matrix T of traceback pointers for strings x and y.
        Returns an alignment string """
    align1, align2 = '', ''
    while T[i][j]!=0: #instead of >, we use equal bc the pointers will reset. where the local alignment starts
        if T[i][j]==1: #came from the diagonal
            align1 = align1 +x[i-1]
            align2=align2 +y[j-1]
            i=i-1 #moves up and left one (diagonal)
            j=j-1
        elif T[i][j]==2: #gap in y, so we move up
            align1=align1+x[i-1]
            align2=align2 +'-'
            i=i-1 
        elif T[i][j]==3: #gap in x
            align1 = align1 + '-'
            align2 = align2 +y[j-1] #add the characyer from  y
            j=j-1
            
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    ## YOUR CODE HERE
    return align1[::-1]+'\n'+align2[::-1] # reverse the strings

f = open("hw4_test21.txt", "r")                                # open the file
p1 = f.readline().strip()                                     # read the first string
p2 = f.readline().strip()                                     # read the second string

pam250 = substitution_matrices.load('PAM250') # possible matrices are ['BENNER22', 'BENNER6', 'BENNER74', 'BLOSUM45', 'BLOSUM50', 'BLOSUM62', 'BLOSUM80', 'BLOSUM90', 'DAYHOFF', 'FENG', 'GENETIC', 'GONNET1992', 'HOXD70', 'JOHNSON', 'JONES', 'LEVIN', 'MCLACHLAN', 'MDM78', 'NUC.4.4', 'PAM250', 'PAM30', 'PAM70', 'RAO', 'RISLER', 'SCHNEIDER', 'STR', 'TRANS']
# pam250 is a numpy matrix
# here is how to access the substitution cost for aminoacid pair (A,M)
# print(pam250.get('A').get('M'))

M,T = localAlignment(p1, p2, pam250, -5)      # compute the dynamic programming matrix and traceback pointers, -5 is the penalty for indel
(i,j) = unravel_index(argmax(M), M.shape)     # index of the max in the matrix using numpy
# The dynamic programming matrix for this input should be
#[[ 0  0  0  0  0  0  0  0]
# [ 0  0  0  0  0  4  0  0]
# [ 0  0  4  1  0  0  4  0]
# [ 0  1  0  4  3  0  1  1]
# [ 0  0  2  2  4  0  0  0]
# [ 0  0  0  0  0 10  5  0]
# [ 0  0  0  0  0  5  7 15]]
print(M.max())                                # alignment score is the max in the matrix
print(tracebackLocal(T, p1, p2, i, j))        # print alignment

1121
NGNQMSWGPVDDEIYSAKFQFVWTRD-NMKWE-EPIFPSSQCDVDDA-EYFIDL-IVEY---EP--WHMCVTPRMLLAFKCF-AR-QDSVFRHLQA--RVERSQVFDIFDCCV-K-W-CWCNEHQTRSHPSM---NETAYAAYD-PIPYLHSNEQVMHEAKWMPHMFW-I-IG-WTFRGSVAEPPPWICISRYTRWVACSQNCLILNWSDDWMEKC-RWSDINWCTAEMRTGIHELEDFSYIYRLHHASFEQRVNGVRVNVGWSCWQDWAMYEIAE-E-Y-WHMLLWSVNPRVAPIY-WSWAIDKPCNYMRWSDEDCGARMHVHIQPLSSCLQRWYNSKQIRVHCCMQKFVNTIKTRCRWFMEPHNPYQPQISKWPWIYYLNEIDMHSYQRMNDVNRTRCQIEQEPPKYDRGRCHATCQPDTSRQQNFFPVEQHLREGSHRIDYGDECLLMPKTGIKIKCYEKYDFDGKDAKIPSWGGAQSNFMGQ--G--REQNPTVHMICKYLHIQTSQTFVLPD-----G--PDMMTWPWY------K--GRDQYTP-KDMSEQRYGI-DIQ-YH-QKY---MHMRISKSFRGATEWIDRIPWAC-RNVAK-RF--R-A--ILVFYQTVRVPVMKLYIFYVEQWCRGRMHAEKARPFWPFEENINMHSNNGRWESV-AWLDGWAWTDKLWELAERFDTWQDTICLH-RDFYYVEESQLTKL-QRNYFPL-MAPYCMCWEDRCSSYRDVPFCYANPDTIVHQYLSRHWEDPYFCDSAQWWIVNIWYTFFPKYNNMGDPKGFEVCPRITIWGYESTHPLLA-PPVK-GQVQNVICCEYSTFDFCGGWS-KTLGT-PKHLMIDSWTPKNSGGPC-RDR-CWET-LMA--VASEI-ECVDVAHYMTCFYTFVRYSTPFIFPTQCAIPKAASEENPFCWLYW-CLHASK--AHISIY-NNMRH
ESHHMH-HPI--VIVVSKY-LKDPMHFQLNHQSEQFFVCNAVG